### ISSUE TITLE
Ruby 2

### ISSUE THREAD

**Issue by DoctorRu** [janlelis/cd#1]
Why this gem need Ruby 2?
Is possible to work with Ruby 1.9.3?

**Comment by janlelis** [comment]
Although Ruby 1.9.3 is a legacy version: https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

it should work with 1.9 as well and I just released 1.0.1 which relaxes the Ruby version requirements  a little.
